codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project: off
    patch: off

flags:
  foundry:
    paths:
      - "coverage/foundry/"
    carryforward: true
  hardhat:
    paths:
      - "coverage/"
    carryforward: true

comment:
  layout: "header, diff, flags"
  behavior: default
  require_changes: no