codecov:
  require_ci_to_pass: yes

flags:
  foundry:
    paths:
      - "coverage/foundry/"
  hardhat:
    paths:
      - "coverage/"

coverage:
  status:
    project:
      default: off
    patch:
      default: off
    foundry:
      target: auto
      threshold: 1%
    hardhat:
      target: auto
      threshold: 1%

comment:
  layout: "header, diff, flags"